// Default config - will be overwritten by sync-client.ts
export const clientConfig = {
  NOM_ENTREPRISE: "Mon Entreprise",
  NOM_DIRIGEANT: "Nom",
  PRENOM_DIRIGEANT: "Prenom",
  GENRE_DIRIGEANT: "masculin",
  TELEPHONE: "00 00 00 00 00",
  TELEPHONE_HREF: "tel:+33000000000",
  EMAIL: "contact@example.com",
  ADRESSE: "1 rue Exemple",
  VILLE: "Paris",
  CODE_POSTAL: "75001",
  DEPARTEMENT: "Paris",
  REGION: "Ile-de-France",
  HORAIRES_SEMAINE: "8h - 18h",
  HORAIRES_SAMEDI: "9h - 12h",
  HORAIRES_DIMANCHE: "Ferme",
  ANNEES_EXPERIENCE: 15,
  NOMBRE_INTERVENTIONS: 500,
  NOTE_GOOGLE: 4.8,
  NOMBRE_AVIS: 45,
  TAUX_SATISFACTION: "98",
  ANNEE_CREATION: 2010,
  SLOGAN: "Votre artisan de confiance",
  DESCRIPTION_ENTREPRISE: "Entreprise artisanale.",
  META_TITLE: "Artisan - Devis Gratuit",
  META_DESCRIPTION: "Artisan professionnel. Devis gratuit.",
  FACEBOOK_URL: "",
  INSTAGRAM_URL: "",
  GOOGLE_URL: "",
  SIRET: "",
  ZONE_INTERVENTION: "Paris et alentours",
  ZONE_KM: "30",
} as const;
export type ClientConfig = typeof clientConfig;
